"""add empresas e setores permissions

Revision ID: 1c5d31037759
Revises: 5d084a7ce82f
Create Date: 2025-07-03 12:07:26.804065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c5d31037759'
down_revision = '5d084a7ce82f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('permission', schema=None) as batch_op:
        batch_op.add_column(sa.Column('can_access_empresas', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('can_access_setores', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('permission', schema=None) as batch_op:
        batch_op.drop_column('can_access_setores')
        batch_op.drop_column('can_access_empresas')

    # ### end Alembic commands ###
