"""sua mensagem

Revision ID: 979e8a318b75
Revises: 
Create Date: 2025-06-26 09:28:52.177179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '979e8a318b75'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('permission', schema=None) as batch_op:
        batch_op.add_column(sa.Column('can_access_register_sector', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('permission', schema=None) as batch_op:
        batch_op.drop_column('can_access_register_sector')

    # ### end Alembic commands ###
